---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[gradle::tarball]

  - name: override
    run_list:
      - recipe[gradle::tarball]
    attributes:
      gradle:
        version: '2.6'
